### ISSUE TITLE
vtk_save() hangs on Windows with "AUX" filename

### ISSUE THREAD

**Issue by juliohm** [jipolanco/WriteVTK.jl#10]
Could you please confirm the following code hangs on Windows? It works just fine on Linux.

```julia
using GeoStatsImages
using WriteVTK

function writevtk(filename, grid)
    nx, ny, nz = size(grid)
    vtkfile = vtk_grid(filename, Float64[1:nx;], Float64[1:ny;], Float64[1:nz;], compress=false)
    vtk_point_data(vtkfile, grid, "facies")
    vtk_save(vtkfile)
end

function thickness(basin)
    AUX = repeat(sum(!isnan(basin),3), inner=[1,1,size(basin,3)])
    AUX = AUX / maximum(AUX)
    AUX[isnan(basin)] = NaN

    AUX
end

GRID = thickness(training_image("Flumy"))

writevtk("AUX", GRID)
```

**Comment by juliohm** [comment]
Actually it doesn't! It is some other issue in the workstation here, sorry for the noise.

**Comment by juliohm** [comment]
The issue is the filename, whenever I set it to `AUX`, the code hangs on Windows.

**Comment by juliohm** [comment]
@jipolanco can you reproduce the issue?

**Comment by jipolanco** [comment]
Sorry, I don't have windows, so I can't reproduce it.

- Is this with Julia 0.4?

- Does it hang after `vtk_grid` or after `vtk_save`?

- Could you test with other filenames: `aux` (lowercase), `Aux`, `TEST`?

- What is the output of `UTF8String("AUX" * ".vtr")`?

**Comment by juliohm** [comment]
I'll get back to you tomorrow when I have access to this Windows
workstation again, I don't know why this particular name is causing the
issue.

-Júlio

**Comment by juliohm** [comment]
Answering all the questions:

* Yes, Julia 0.4.1
* It hangs somewhere in `vtk_save`
* It hangs with AUX and Aux, but doesn't hang with TEST
* The output is "AUX.vtr" as expected

**Comment by juliohm** [comment]
Windows is weird!

http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/
