### ISSUE TITLE
Unicode names for DataArrays get garbled

### ISSUE THREAD

**Issue by KristofferC** [jipolanco/WriteVTK.jl#11]
A greek gamma gets turned to `Î³` for example. I have tried in pure LightXML and there it works fine to set a tag with a unicode string so there must be some conversion here that goes wrong. Haven't found where yet.

**Comment by jipolanco** [comment]
Do you see the problem when you open the VTK file in a text editor, or in Paraview (or similar), or both? If it's in a text editor, is the file opened with utf-8 encoding?
I just did some tests with unicode strings (such as α) which show up correctly in vim, but fail to render in Paraview.

**Comment by KristofferC** [comment]
For me it is in editors too (sublime and vim):

![image](https://cloud.githubusercontent.com/assets/1282691/16096809/fa178ddc-334a-11e6-9733-10b59e5ad4f2.png)

Looking at it closer I think it is just the file encoding that is wrong. When I manually change to a unicode letter it is garbled in Paraview anyway so nothing really to do here.
