### ISSUE TITLE
Automatically insert zeros if points are given in dimension 1 or 2

### ISSUE THREAD

**Issue by KristofferC** [jipolanco/WriteVTK.jl#12]
Do you think it makes sense to allow to give the `points` array to `vtk_grid` as a matrix with either one or two rows and then complete the last row with zeros?

**Comment by jipolanco** [comment]
Yes! That's definitely something that would be useful. I'll just need to figure out the best way to implement it, but it should be quite simple.

**Comment by jipolanco** [comment]
Closed by  aac07d4
