### ISSUE TITLE
Sparse point set representation

### ISSUE THREAD

**Issue by juliohm** [jipolanco/WriteVTK.jl#13]
Suppose I have a small number of points with values as a list:

>x1 y1 z1 val1
x2 y2 z2 val2
...

What would be a good VTK format to display this cloud? Currently I am saving the full grid even though only a few points are active (sparse grid).

**Comment by jipolanco** [comment]
This would correspond to an unstructured grid.
Assuming you have `N` points with values, you could do something like:
```julia
cells = [MeshCell(VTKCellType.VTK_VERTEX, n) for n = 1:N]
vtk = vtk_grid("filename", x, y, z, cells)
vtk_point_data(vtk, val)
vtk_save(vtk)
```

**Comment by juliohm** [comment]
Thank you Juan, I will try it out.

**Comment by juliohm** [comment]
@jipolanco what is the dimension of the arrays x, y, z in this case?

**Comment by jipolanco** [comment]
The arrays x, y, z and val would all be vectors of length N.

**Comment by juliohm** [comment]
I don't know what is wrong with this function, it is raising an error related to the types Int32 vs Int64 somewhere:

```julia
function writevtkHD(filename, harddata)
    N = length(harddata)
    X = [Float64[k...] for k in keys(harddata)]
    X = hcat(X...)'
    cells = [MeshCell(VTKCellType.VTK_VERTEX, n) for n = 1:N]
    vtkfile = vtk_grid("filename", X[:,1], X[:,2], X[:,3], cells)
    vtk_point_data(vtkfile, values(harddata))
    vtk_save(vtkfile)
end
```

You can call it with for example:

```julia
data = Dict{NTuple{3,Integer},Real}()
data[1,1,1] = 1
data[2,1,1] = 2
writevtkHD("foo", data)
```

**Comment by juliohm** [comment]
@jipolanco can you please give some hint on why the code above doesn't work?

**Comment by jipolanco** [comment]
I haven't had the time to test your code yet, and I don't really know 
where the error could come from. I'll let you know when I find some time 
to test it.

**Comment by jipolanco** [comment]
The code doesn't work because I made a little mistake above (sorry!). The `cells` array should be:
```julia
cells = [MeshCell(VTKCellType.VTK_VERTEX, [n]) for n = 1:N]
```
Note that the `n` is now enclosed by brackets `[]`, making it a one-element array.

On the other hand, the code will now fail when calling `vtk_point_data`, since this function doesn't accept the type returned by `values(harddata)`, which is a `ValueIterator`. You would need to convert it to an array before calling `vtk_point_data`.

**Comment by juliohm** [comment]
Thank you @jipolanco , I will take a look into it again. Was busy with other things...
