### ISSUE TITLE
could not load library "libxml2"

### ISSUE THREAD

**Issue by m3m0ry** [jipolanco/WriteVTK.jl#15]
Hello,
i have a probably more dumb issue, however i still didn't manage to solve it.

I wanted to create some output of my simulation (rectilinear grid). However if my simulation comes to the function "vtk_point_data", julia will just report:

ERROR: LoadError: error compiling visualization: error compiling vtk_point_data: error compiling vtk_point_or_cell_data: error compiling root: could not load library "libxml2"
libxml2: cannot open shared object file: No such file or directory

However, i know that this lib is installed since:
sudo ldconfig -p G libxml2
libxml2.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libxml2.so.2

Should i export something? How? What am i missing?
(i am new to julia, so this might be a dumb mistake)

**Comment by m3m0ry** [comment]
Ok, if i set the Libdl.DL_LOAD_PATH properly and search for "libxml2.so.2" then i found it:

julia> push!(Libdl.DL_LOAD_PATH, "/usr/lib")
1-element Array{ByteString,1}:
 "/usr/lib"

Libdl.find_library(["libxml2.so.2"], [])
"libxml2.so.2"

But how am i supposed to fix the script?

**Comment by jipolanco** [comment]
Sorry I can't help you too much at this time, I'm on vacation... Can you check if you have the libxml2-devel package installed? The name might vary according to your linux distribution.

**Comment by m3m0ry** [comment]
Yep, that fixed it. Thank you very much.
