### ISSUE TITLE
Helper function for image data

### ISSUE THREAD

**Issue by juliohm** [jipolanco/WriteVTK.jl#26]
I often see myself saving Julia arrays (3D image data) with the helper function below:

```julia
function writevtk(filename, grid, varname="var")
    vtkfile = vtk_grid(filename, size(grid)...)
    vtk_point_data(vtkfile, grid, varname)
    vtk_save(vtkfile)
end

writevtk("foo", rand(30,30,30))
```

Can we have it included in the package? It would save me from carrying this definition everywhere in a hacked script loaded in `.juliarc.jl`. If you give me the green light, I can submit the PR.

**Comment by jipolanco** [comment]
I'm sorry, I don't think it makes much sense to define such a function in the package, since it's associated to a quite specific use case (i.e. a specific type of grid, a single data array). I can't think of a better solution than to define the function in `.juliarc.jl` or at the beginning of a Julia script...

**Comment by juliohm** [comment]
Isn't that a very common specific use case? Saving Julia arrays in vtk
format.

-Júlio

On Jan 20, 2017 4:42 AM, "Juan Ignacio Polanco" <notifications@github.com>
wrote:

I'm sorry, I don't think it makes much sense to define such a function in
the package, since it's associated to a quite specific use case (i.e. a
specific type of grid, a single data array). I can't think of a better
solution than to define the function in .juliarc.jl or at the beginning of
a Julia script...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jipolanco/WriteVTK.jl/issues/26#issuecomment-274063601>,
or mute the thread

**Comment by jipolanco** [comment]
Oh, you mean as a way to visualise any Julia array? If you put it that way, that sounds very useful! I'm sorry, I just didn't see it that way earlier. Just submit the PR and I'll take a look at it. If you don't mind, I'll probably change the name of the function.

**Comment by juliohm** [comment]
Thanks Juan, I will submit the PR soon.

Best,
-Júlio
