### ISSUE TITLE
Use LIbz.jl instead of Zlib.jl

### ISSUE THREAD

**Issue by KristofferC** [jipolanco/WriteVTK.jl#3]
Just wanted to make you aware that there is a faster version of the interface to Zlib now available. You can find it here: https://github.com/BioJulia/Libz.jl.

Upgrading should be quite painless.

However, I believe that package is 0.4 only.

**Comment by jipolanco** [comment]
Thanks, I didn't know about that package. I'll see if I can upgrade to Libz and still keep Zlib for compatibility with 0.3.

**Comment by KristofferC** [comment]
Since 0.4 is at release candidate level it could be time to tag a final version for 0.3 and then develop purely for 0.4.

**Comment by jipolanco** [comment]
That's a good point, I guess I'll remove compatibility with 0.3 in future versions.

**Comment by KristofferC** [comment]
Cool,  thanks.

**Comment by jipolanco** [comment]
Sorry for the delay :)

**Comment by KristofferC** [comment]
No worries. It worked very well anyway :)
