### ISSUE TITLE
Using VTKCellTypes and VTKCellType

### ISSUE THREAD

**Issue by mohamed82008** [jipolanco/WriteVTK.jl#32]
I am trying to import VTKCellType from VTKCellTypes but I get an error. Please see the details in this link [https://discourse.julialang.org/t/how-to-make-all-functions-in-a-submodule-of-an-external-module-visible/4106/4].

**Comment by fredrikekre** [comment]
What's not working?

```julia
julia> using WriteVTK

julia> import WriteVTK.VTKCellTypes.VTKCellType

julia> VTKCellType
WriteVTK.VTKCellTypes.VTKCellType
```

**Comment by jipolanco** [comment]
@fredrikekre's solution works just fine. Alternatively, if you just want `VTKCellType`:

```julia
import WriteVTK.VTKCellTypes.VTKCellType
```

**Comment by fredrikekre** [comment]
From the discourse thread it seems like there is a confusion since `VTKCellType` is exported from the `WriteVTK` module, but not from the `VTKCellTypes` module. That's a result of the renaming, ref #18 and #21. I don't think there is any issue here.

**Comment by jipolanco** [comment]
You're right. I'll remove the deprecated module name and the `export VTKCellType` to avoid confusions.

**Comment by fredrikekre** [comment]
> You're right. I'll remove the deprecated module name and the export VTKCellType to avoid confusions.

Only if we drop support for Julia 0.4. https://github.com/jipolanco/WriteVTK.jl/blob/06343d7fbbbc2e7b47d95ef39d7d2356d1e0efe1/src/WriteVTK.jl#L27-L31

**Comment by jipolanco** [comment]
True, people using Julia 0.4 may not know about the renaming since they don't see a warning... I was planning on dropping support for 0.4 anyways, but maybe we should wait for Julia 0.6 to be released (very soon I guess).

**Comment by mohamed82008** [comment]
I would like to have access to all identifies in the VTKCellTypes module without having to import them one by one with their module path. It would be inconvenient to have to write the whole path WriteVTK.VTKCellTypes.VTKCellType.

**Comment by fredrikekre** [comment]
Well, thats how things work in Julia, note though that you only have to use `import WriteVTK.VTKCellTypes.VTKCellType` once, and then you can use `VTKCellType` as usual (without the full qualifier).
