### ISSUE TITLE
Don't allocate for each MeshCell

### ISSUE THREAD

**Issue by haampie** [jipolanco/WriteVTK.jl#38]
The Meshcell type forces to allocate a very large amount of small vectors in some applications:

```
struct MeshCell
    ctype::VTKCellTypes.VTKCellType
    connectivity::Vector{Int32} # <--- this guy
end
```

I think a more idiomatic way is to parametrize the connectivity type

```
struct MeshCell{Tc <: AbstractVector{<:Integer}}
  ctype::VTKCellTypes.VTKCellType
  connectivity::Tc
end
```

That way I can store the connectivity array without further allocations when using StaticArrays

```
MeshCell(VTK_TRIANGLE, SVector{3}(1, 2, 3))
```

**Comment by jipolanco** [comment]
That's a good point, thanks for the idea. I just modified the definition of MeshCell following what you propose, see 1850714.
