### ISSUE TITLE
Parametric type breaks some working code

### ISSUE THREAD

**Issue by tribut** [jipolanco/WriteVTK.jl#39]
With the introduction of the parametric type to `MeshCell`, the following no longer works:

~~~
using WriteVTK
# pointless test data
tetra = reshape(1:40, (:,4))
points = rand(3,10)
# this used to work
cells = [MeshCell(VTKCellTypes.VTK_TETRA, tetra[i,:])
    for i=1:size(tetra, 1)]
vtk_grid("test", points, cells)
~~~

This is because MeshCell now returns something like `MeshCell{Array{Int64,1}}` and vtk_grid will only accept an array of `WriteVTK.MeshCell`.

The error is

~~~
ERROR: LoadError: MethodError: no method matching vtk_grid(::String, ::Array{Float64,2}, ::Array{WriteVTK.MeshCell{Array{Int64,1}},1})
Closest candidates are:
  vtk_grid(::WriteVTK.MultiblockFile, ::Any...; kwargs...) at /home/felix/.julia/v0.6/WriteVTK/src/gridtypes/multiblock.jl:20
  vtk_grid(::AbstractString, ::AbstractArray{T,2}, ::Array{WriteVTK.MeshCell,1}; kwargs...) where T at /home/felix/.julia/v0.6/WriteVTK/src/gridtypes/unstructured.jl:74
  vtk_grid(::AbstractString, ::AbstractArray{T,2}, ::AbstractArray{T,2}; kwargs...) where T at /home/felix/.julia/v0.6/WriteVTK/src/gridtypes/structured.jl:86
~~~

The [tests explicitly initialize an array without parametric type](https://github.com/jipolanco/WriteVTK.jl/blob/47a53931c859ecde641538105450846276ec5a41/test/unstructured.jl#L32), so this is not an issue here. I think it makes sense for the functions to also accept the new type.

Running Julia 0.6.2

**Comment by tribut** [comment]
Thanks!

**Comment by jipolanco** [comment]
Sorry about that, and thanks for opening an issue. I had forgotten to update the `vtk_grid` functions for unstructured grids after the `MeshCell` update, and as you say the tests did not caught the issue.

I just commited a fix. Let me know if you keep getting problems.
