### ISSUE TITLE
Why limit data to 1 or 3 dimensions?

### ISSUE THREAD

**Issue by KristofferC** [jipolanco/WriteVTK.jl#4]
Hello,

I see no reason for the dimension check here: https://github.com/jipolanco/WriteVTK.jl/blob/2928fac004287e509e021bfea75f894c6ab888ed/src/gridtypes/common.jl#L157

Paraview has no problems with dimensions other than 1 and 3. It is for example common to export symmetric 2nd order tensors as 6 dimensional and unsymmetric 2nd order tensors as 9 dimensional cell data.

**Comment by jipolanco** [comment]
You're right, thanks. When I wrote that, I was thinking on one of my applications.

I just removed the dimension check in commit 5d793fc90d87431cf2d9c9c9cb9e45c9180af68c.

**Comment by KristofferC** [comment]
Thanks!
