### ISSUE TITLE
Memory leak with compression enabled?

### ISSUE THREAD

**Issue by carlomontec** [jipolanco/WriteVTK.jl#43]
Hi,

thank you all for your great work of WriteVTK.

Via a PVD collection file, I am creating the animation of an dynamic  FEM simulation.
  
For every time step, I update the mesh definition according to the displacements of the time step and give as point data the velocities per node. It is very similar  as in test file: `pvdCollection.jl`

If I save it as a PVD file, I can see how the memory use increases significantly as each of the VTU files per timesteps being created. It would look like every VTU file is in RAM before being written to the disk.

The strange part is that after writing the files to disk, the RAM use still is very high. It doesn't decrease 
until I exit Julia.  I have 3000 time steps. For all files, a total of ~440MB of disk is used, but julia uses as much as 6Gb of RAM for creating the files. 

Is there a way to release memory after correctly saving to disk a VTU file?

**Comment by fredrikekre** [comment]
See also  #34, which was meant to fix this issue...

**Comment by jipolanco** [comment]
Hi, I looked quickly into the issue and I think I was able to reproduce it
with a modified version of the `pvdCollection.jl` test file.

I suspect it might be an issue of the libxml2 C library, used to write the
VTK XML files, which apparently doesn't play well with the Julia garbage
collector. I'll test some workarounds when I find some time.

**Comment by jipolanco** [comment]
After some tests, the issue seems to be related to data compression. As a workaround, you can disable compression with `compress=false` when calling `vtk_grid`, which should fix the memory problems.

**Comment by carlomontec** [comment]
gonna give it a try, thanks!

**Comment by jipolanco** [comment]
I'm reopening this as it's clearly a bug.

It would be nice to have some code that reproduces the issue.

**Comment by fredrikekre** [comment]
Memory usage also doesn't go down when the function returns (for the `compress=true` case), so probably this memory is outside of Julia memory management as suggested in https://github.com/jipolanco/WriteVTK.jl/issues/43#issuecomment-418024985
