### ISSUE TITLE
Can I use this package to plot a 3D surface (in paraview), if so how should I write VTK file?

### ISSUE THREAD

**Issue by WangWei90** [jipolanco/WriteVTK.jl#46]
Thank you in advance!
I have used this package to view 3D scanning images. Now, I want to use it to view some 3D surface, is it possible?
For example, I extract this from GR framework for julia bindings ()

```julia
# Create example point data
x = 8 .* rand(100) .- 4
y = 8 .* rand(100) .- 4
z = sin.(x) .+ cos.(y)
# Draw the surface plot
surface(x, y, z)
# Create example grid data
X = LinRange(-2, 2, 40)
Y = LinRange(0, pi, 20)
x, y = meshgrid(X, Y)
z = sin.(x) .+ cos.(y)
# Draw the surface plot
surface(x, y, z)
# Draw the surface plot using a callable
surface(x, y, sin.(x) .+ cos.(y))
```
![3D surface](https://gr-framework.org/_images/surface.png)

PS, I am not an expert in paraview, please tell me more details if possible.

**Comment by juliohm** [comment]
This package is for writing VTK files to disk. Your question seems to be about what VTK format would be appropriate or how to use ParaView to visualize surfaces. I suggest to ask the question somewhere else like the Discourse forum or slack.
