### ISSUE TITLE
Error loading VTI written by vtk_write_array

### ISSUE THREAD

**Issue by juliohm** [jipolanco/WriteVTK.jl#49]
I found this bug today that is preventing me from continuing with my work:

```julia
A = rand(Float32,320,320,80)

vtk_write_array("foo", A)
vtk_write_array("bar", (A,A,A), ("A","B","C"))
```

The file `foo.vti` works fine in ParaView, but the file `bar.vti` does not. The error message the ParaView shows:

<img width="566" alt="ParaViewLog" src="https://user-images.githubusercontent.com/3345261/57796172-1e255c80-771e-11e9-869f-531df2cd53ed.png">

I appreciate if you can take a quick look at it.

Thank you,

**Comment by jipolanco** [comment]
Hi, have you tried disabling compression? You would need to pass `compress=false` to `vtk_grid` (in the current version you can't pass keyword parameters to the `vtk_write_array` wrapper, but that could be changed...).

**Comment by juliohm** [comment]
Hi Juan,

Do you have a workaround for now? Why compression is breaking the load in
ParaView?

**Comment by jipolanco** [comment]
From the message you get I guess it's a compression problem. I'll look into it when I have the time.

If compression is the problem, you could try doing something like this:

```julia
vtk_grid(filename, size(A)..., compress=false) do vtk
    # add arrays as vtk_point_data...
end
```

**Comment by juliohm** [comment]
Thank you Juan for the quick response. I will try the workaround.
