### ISSUE TITLE
File save path

### ISSUE THREAD

**Issue by Elliothuo** [jipolanco/WriteVTK.jl#50]
WriteVTK.jl is great. It solves the problem of post-processing display in finite element calculation. 👍 
I want to ask how to specify the save path of the generated `.vtu` file.

**Comment by jipolanco** [comment]
I'm glad you find WriteVTK useful!

If I understand correctly, you want to save a `vtu` file to a directory other than the current path? In that case, this should work as expected:
```julia
savedir = "output"
mkpath(savedir)
basename = joinpath(savedir, "my_vtk_file")
vtk = vtk_grid(basename, [...])
```
