### ISSUE TITLE
VTKCelltype from integer id

### ISSUE THREAD

**Issue by fverdugo** [jipolanco/WriteVTK.jl#56]
Hi!

is there any function in the package, that, given an integer representing the vtk id of a cell topology, returns the corresponding `VTKCellType` object defined in the module `VTKCellTypes.VTK`?

That is, if this function is called `vtk_cell_type_from_id`, then  `vtk_cell_type_from_id(9)` would return the constant `VTKCellTypes.VTK_QUAD`, `vtk_cell_type_from_id(5)` would return `VTKCellTypes.VTK_TRIANGLE`, etc.

If  this is not available, I can add it via a PR.

Best!

**Comment by jipolanco** [comment]
That's a good idea!

No, that's not implemented right now. Sure, feel free to send a PR.

I think that it could be implemented as a constructor of `VTKCellType`, something like `VTKCellType(id::Integer) = ...`.

**Comment by fverdugo** [comment]
I have added the constructor, see PR #57

**Comment by jipolanco** [comment]
Closed by #57
