### ISSUE TITLE
Auxiliary data in VTK files

### ISSUE THREAD

**Issue by henry2004y** [jipolanco/WriteVTK.jl#65]
Hi,

I'm wondering if the XML based VTK files can support adding auxiliary data or header information? For example, how can I include a time tag inside the generated file?

**Comment by jipolanco** [comment]
Hi, I guess it would be possible to add more information inside custom XML tags, although this would only be useful if you have a custom VTK reader. There might be an "official" way to do this in the VTK libraries, but I don't really know about this. In particular, I'm not aware of any way to include time information in VTK files.

May I ask what is your use case? Specifically regarding time tags, the usual way to do this is using PVD files, which [we support](https://github.com/jipolanco/WriteVTK.jl#paraview-data-pvd-file-format), but they're specific to Paraview as far as I'm aware.

**Comment by henry2004y** [comment]
Thanks for the quick reply! Actually I have tried PVD files, and for time tags only it works. However,  it doesn't allow me to add more information. I am working on converting some Tecplot ASCII files into VTK. In Tecplot format, you are allowed to include a `AUXDATA` tag in the header with all kinds of information you want. Currently with the help of your package, I can convert the critical parameters like number of cells, number of nodes, etc., but the extra string information is lost.

I am not familiar with XML. It would be perfect if we can add extra info into the XML based VTK files and read through ParaView. This is not a critical issue, but somehow annoying.

**Comment by henry2004y** [comment]
Hi,

Sorry to bother you again! I have tested the new `fielddata` feature. For the image data as you did in the test files, ParaView can successfully read the data. However, for my unstructured grid data, ParaView just crashed at the time when I clicked read. Here is a sample generated VTU file that will crash:
[out.vtu.zip](https://github.com/jipolanco/WriteVTK.jl/files/4711832/out.vtu.zip)

I have tried both string and Int32 type `fielddata`, and neither work. Do you know what is the possible cause for this issue?

**Comment by jipolanco** [comment]
I'll look into this. Can you provide a minimum example that reproduces the issue?

**Comment by henry2004y** [comment]
Hold on. Maybe there are issues with my original data. I'll check again first.
