### ISSUE TITLE
InexactError in Julia v0.4

### ISSUE THREAD

**Issue by juliohm** [jipolanco/WriteVTK.jl#7]
Can you reproduce the error in Julia v0.4?

```julia
using WriteVTK
nx = ny = nz = 10
G = rand(nx, ny, nz)
vtkfile = vtk_grid("/tmp/grid", Float64[1:nx;], Float64[1:ny;], Float64[1:nz;])
```

>LoadError: InexactError()
while loading In[21], in expression starting on line 6

> in _unsafe_batchsetindex! at multidimensional.jl:329
 in data_to_xml at /home/juliohm/.julia/v0.4/WriteVTK/src/gridtypes/common.jl:73
 in vtk_grid at /home/juliohm/.julia/v0.4/WriteVTK/src/gridtypes/rectilinear.jl:35

The code used to work in Julia v0.5.

I would like to take this opportunity and ask if you feel that a function for VTK images should be added (i.e. rectilinear grids indexed by integers with unit spacing). For instance, I often do:

```julia
function vtk_image(filename, grid)
    nx, ny, nz = size(grid)
    vtkfile = vtk_grid(filename, Float64[1:nx;], Float64[1:ny;], Float64[1:nz;])
    vtk_point_data(vtkfile, grid, "property")
    vtkfile
end
```

**Comment by jipolanco** [comment]
Yes, I can reproduce it in Julia 0.4. Thanks for letting me know. This seems to be related to a recent update of the BufferedStreams package, the same problem of issue #8. I'll look into it.

Adding support for VTK images can be interesting, and shouldn't be very difficult. I'll see what I can do!

**Comment by juliohm** [comment]
Thank you @jipolanco, I am moving with other research tasks while you fix the issue. WriteVTK is very useful!

**Comment by jipolanco** [comment]
In the meantime you can disable compression when creating VTK files to workaround the issue:

```julia
vtkfile = vtk_grid([...], compress=false)
```

Glad to know that it's useful for you!

**Comment by juliohm** [comment]
Thank you for the workaround, it will save me time for sure!
