### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by AhmedSalih3d** [jipolanco/WriteVTK.jl#73]
# Create lists of lines and polygons connecting different points in space
points = rand(3, 100)  # (x, y, z) locations
lines = [MeshCell(PolyData.Lines(), (i, i + 1, i + 4)) for i in (3, 5, 42)]
polys = [MeshCell(PolyData.Polys(), i:(i + 6)) for i = 1:3:20]
vtk = vtk_grid(points, lines, polys)

Last line should have a parameter more "vtk_grid("name_of_file", ...)

**Comment by jipolanco** [comment]
You're totally right, thanks!
