### ISSUE TITLE
Option for format of output

### ISSUE THREAD

**Issue by lijas** [jipolanco/WriteVTK.jl#75]
Would it be possible to add an option for outputing data arrays in ascii instead of binary?
Sometimes I want to inspect the output of the vtk file

```
<DataArray type="Float64" Name=".." format="ascii"...

<DataArray type="Float64" Name=".." format="binary"...
```

**Comment by jipolanco** [comment]
Yes, that should be relatively easy to implement, and would be good to have. I'll see what I can do.
